@echo off
setlocal

for %%T in (
    GATEWAY_HTTP VALIDADOR1_HTTP VALIDADOR2_HTTP REPOSITORIO1_HTTP REPOSITORIO2_HTTP
    GATEWAY_TCP VALIDADOR1_TCP VALIDADOR2_TCP REPOSITORIO1_TCP REPOSITORIO2_TCP
    GATEWAY_UDP VALIDADOR1_UDP VALIDADOR2_UDP REPOSITORIO1_UDP REPOSITORIO2_UDP
    GATEWAY_GRPC VALIDADOR1_GRPC VALIDADOR2_GRPC REPOSITORIO1_GRPC REPOSITORIO2_GRPC
) do (
    taskkill /FI "WINDOWTITLE eq %%T" /T /F >nul 2>&1
)

echo Encerramento concluido.
exit /b 0